#!/usr/bin/env bash
# <Script Name>
# <Description what this module does>
# Written by <Author>
# GPL V3
########


# Source error handling, leave this in place
set -x
set -e

source /common.sh
install_cleanup_trap

unpack /filesystem/home/pi /home/pi pi
unpack /filesystem/home/root /root root
unpack /filesystem/boot /boot

echo "This is an example module, install and set up what you need here!"
echo "$RASPBIAN64_VAR"

# Unpack root at the end, so files are modified before
unpack /filesystem/root /

apt-get update
apt-get install -y debootstrap debian-archive-keyring schroot


 debootstrap --arch arm64 buster /chroot64

pushd /chroot64
find . -depth | while read f
do
    if file -L "$f" | grep -q ELF
        then
            echo "$f" >> /chroot64/bins.txt
    fi
done
popd
echo "./etc/ld.so.cache" >> /chroot64/bins.txt
cp /64bit_chroot /chroot64/64bit_chroot
chroot /chroot64 /bin/bash /64bit_chroot
mv /run_docker /chroot64/run_docker

# Add systemd service
systemctl enable chroot_docker.service


echo arm_64bit=1 >> /boot/config.txt
