#!/bin/bash
apt-get update
apt-get -y install curl cgroupfs-mount python3 python3-distutils python3-dev wget gcc libffi-dev build-essential libssl-dev
curl -sSL get.docker.com | sh

# Install docker-compose
wget https://bootstrap.pypa.io/get-pip.py -O - | python3
pip3 install docker-compose
