version: '3.6'

services:
  custompios:
    image: guysoft/custompios:devel
    container_name: raspbian64-build
    tty: true
    restart: always
    privileged: true
    volumes:
      - ./:/distro
      # - /home/guy/workspace/custom_raspberrypi_os/CustomPiOS/src:/CustomPiOS
    devices:
      - /dev/loop-control

